// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TechAssistPro.Scheduling.Data;

#nullable disable

namespace TechAssistPro.Scheduling.Migrations
{
    [DbContext(typeof(SchedulingDbContext))]
    [Migration("20251221103346_InitialSchedulingSchema")]
    partial class InitialSchedulingSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TechAssistPro.Scheduling.Entities.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUpdatedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ReassignmentCount")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SupportAgentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TicketId")
                        .IsUnique();

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("TechAssistPro.Scheduling.Entities.SupportAgent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("ActiveAssignments")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUpdatedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SupportAgents");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            ActiveAssignments = 0,
                            CreatedAtUtc = new DateTime(2025, 12, 21, 10, 33, 45, 778, DateTimeKind.Utc).AddTicks(1944),
                            IsDeleted = false,
                            Name = "Arjun"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            ActiveAssignments = 0,
                            CreatedAtUtc = new DateTime(2025, 12, 21, 10, 33, 45, 778, DateTimeKind.Utc).AddTicks(1947),
                            IsDeleted = false,
                            Name = "Priya"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            ActiveAssignments = 0,
                            CreatedAtUtc = new DateTime(2025, 12, 21, 10, 33, 45, 778, DateTimeKind.Utc).AddTicks(1948),
                            IsDeleted = false,
                            Name = "Rohit"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            ActiveAssignments = 0,
                            CreatedAtUtc = new DateTime(2025, 12, 21, 10, 33, 45, 778, DateTimeKind.Utc).AddTicks(1949),
                            IsDeleted = false,
                            Name = "Sneha"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            ActiveAssignments = 0,
                            CreatedAtUtc = new DateTime(2025, 12, 21, 10, 33, 45, 778, DateTimeKind.Utc).AddTicks(1949),
                            IsDeleted = false,
                            Name = "Karthik"
                        });
                });

            modelBuilder.Entity("TechAssistPro.Scheduling.Entities.SupportAgent", b =>
                {
                    b.OwnsOne("TechAssistPro.Scheduling.Entities.AgentAvailability", "Availability", b1 =>
                        {
                            b1.Property<Guid>("SupportAgentId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("IsAvailable")
                                .HasColumnType("boolean")
                                .HasColumnName("IsAvailable");

                            b1.HasKey("SupportAgentId");

                            b1.ToTable("SupportAgents");

                            b1.WithOwner()
                                .HasForeignKey("SupportAgentId");

                            b1.HasData(
                                new
                                {
                                    SupportAgentId = new Guid("11111111-1111-1111-1111-111111111111"),
                                    IsAvailable = true
                                },
                                new
                                {
                                    SupportAgentId = new Guid("22222222-2222-2222-2222-222222222222"),
                                    IsAvailable = true
                                },
                                new
                                {
                                    SupportAgentId = new Guid("33333333-3333-3333-3333-333333333333"),
                                    IsAvailable = true
                                },
                                new
                                {
                                    SupportAgentId = new Guid("44444444-4444-4444-4444-444444444444"),
                                    IsAvailable = true
                                },
                                new
                                {
                                    SupportAgentId = new Guid("55555555-5555-5555-5555-555555555555"),
                                    IsAvailable = true
                                });
                        });

                    b.OwnsMany("TechAssistPro.Scheduling.Entities.Skill", "Skills", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Category")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<int>("Level")
                                .HasColumnType("integer");

                            b1.Property<Guid>("SupportAgentId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("SupportAgentId");

                            b1.ToTable("SupportAgentSkills", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SupportAgentId");

                            b1.HasData(
                                new
                                {
                                    Id = new Guid("896bf62d-0cab-475e-90cb-abbafe6ae1ee"),
                                    Category = "Hardware",
                                    Level = 3,
                                    SupportAgentId = new Guid("11111111-1111-1111-1111-111111111111")
                                },
                                new
                                {
                                    Id = new Guid("2c5084bc-1f3a-42ad-9104-7b45ba83232e"),
                                    Category = "Network",
                                    Level = 2,
                                    SupportAgentId = new Guid("11111111-1111-1111-1111-111111111111")
                                },
                                new
                                {
                                    Id = new Guid("b43d4c07-c805-4d56-9fbd-d1401d0345d5"),
                                    Category = "Software",
                                    Level = 3,
                                    SupportAgentId = new Guid("22222222-2222-2222-2222-222222222222")
                                },
                                new
                                {
                                    Id = new Guid("b95d270a-b7f5-49f7-8c08-4bc62737b7d8"),
                                    Category = "Database",
                                    Level = 2,
                                    SupportAgentId = new Guid("33333333-3333-3333-3333-333333333333")
                                },
                                new
                                {
                                    Id = new Guid("b8dd0cd4-0c91-4788-a7c8-7d1b826e1a3f"),
                                    Category = "Software",
                                    Level = 2,
                                    SupportAgentId = new Guid("33333333-3333-3333-3333-333333333333")
                                },
                                new
                                {
                                    Id = new Guid("12dd110b-38fc-47d4-9ff0-ad5cda65fee1"),
                                    Category = "Network",
                                    Level = 3,
                                    SupportAgentId = new Guid("44444444-4444-4444-4444-444444444444")
                                },
                                new
                                {
                                    Id = new Guid("a5b043d5-0c45-43e9-bfe8-184fbea25cce"),
                                    Category = "Hardware",
                                    Level = 2,
                                    SupportAgentId = new Guid("55555555-5555-5555-5555-555555555555")
                                });
                        });

                    b.Navigation("Availability")
                        .IsRequired();

                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
